server:
  port: 8081
  servlet:
    context-path: /mall

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    format:
      date: "yyyy-MM-dd"
      date-time: "yyyy-MM-dd HH:mm:ss"
      time: "HH:mm:ss"

  jackson:
    time-zone: GMT+1
    date-format: "yyyy-MM-dd HH:mm:ss"
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false

  datasource:
    url: jdbc:h2:file:./h2db/xxmall;DB_CLOSE_DELAY=-1;
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver

  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console

  thymeleaf:
    cache: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: true

logging:
  level:
    priv:
      jesse:
        mall: INFO